#https://lhcb.github.io/analysis-essentials/git/11-ci.html
#https://github.com/clelange/cmssw-docker
image: index.docker.io/clelange/cc7-cms:latest

stages:
    - build
    - test

before_script:
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - export CI_HOME="$( pwd )"
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config
  - echo "${KRB_PASSWORD}" | kinit -f ${KRB_USERNAME}@CERN.CH
  - klist
  - scp -v -o StrictHostKeyChecking=no ${KRB_USERNAME}@lxplus.cern.ch:~/x509 ~/x509
  - export X509_USER_PROXY=~/x509
  - voms-proxy-info --all
  - git config --global user.name 'CERN CI'
  - git config --global user.email 'joosep.pata@cern.ch'
  - git config --global user.github jpata
  - source setup.sh

build-looper:
    tags: [ cvmfs ]
    stage: build
    script:
      - cd $CI_HOME
      - make
      - cd ..
      - tar -czf nanoflow.tgz nanoflow
      - du -csh nanoflow.tgz
      - mv $CI_HOME/../nanoflow.tgz $CI_HOME
    artifacts:
        paths:
            - nanoflow.tgz

run-looper:
    tags: [ cvmfs ]
    stage: test
    script:
      - cd $CI_HOME
      - mv nanoflow.tgz ../
      - cd ..
      - rm -Rf nanoflow
      - tar xf nanoflow.tgz
      - cd nanoflow
      - pwd
      - ls -al
      - ./bin/nf data/input_xrootd.json out.json

run-looper-py:
    tags: [ cvmfs ]
    stage: test
    script:
      - cd $CI_HOME
      - mv nanoflow.tgz ../
      - cd ..
      - rm -Rf nanoflow
      - tar xf nanoflow.tgz
      - cd nanoflow
      - pwd
      - ls -al
      - python python/looper.py data/input_xrootd.json out.json
