stages:
    - build
    - test

before_script:
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - export CI_HOME="$( pwd )"
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config
  - echo "${KRB_PASSWORD}" | kinit -f ${KRB_USERNAME}@CERN.CH
  - klist
  - scp -v -o StrictHostKeyChecking=no ${KRB_USERNAME}@lxplus.cern.ch:~/x509 ~/x509
  - export X509_USER_PROXY=~/x509
  - voms-proxy-info --all
  - git config --global user.name 'CERN CI'
  - git config --global user.email 'joosep.pata@cern.ch'
  - git config --global user.github jpata
  - source setup.sh

build-looper:
    tags: [ cvmfs ]
    stage: build
    script:
      - cd nanoflow
      - make
      - cd ..
      - tar -czf nanoflow.tgz nanoflow
      - du -csh nanoflow.tgz
      - mv $CI_HOME/../nanoflow.tgz $CI_HOME
    artifacts:
        paths:
            - nanoflow.tgz

run-looper:
    tags: [ cvmfs ]
    stage: test
    script:
      - export CI_HOME="$( pwd )"
      - cd $CI_HOME/..
      - tar xfz $CI_HOME/nanoflow.tgz
      - ls -al
      - cd $CI_HOME/nanoflow
      - source setup.sh
      - ./bin/looper data/input_xrootd.json out.json
